version: '3'
services:
  applisoccerserver:
    image: 922577824254.dkr.ecr.us-east-1.amazonaws.com/applisoccer:1.0
    ports:
      - 5001:5001
      - 5000:5000
  mongodb:
    image: mongo 
    ports: 
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes: 
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
    